### ISSUE TITLE
Crash on Application Boot

### ISSUE THREAD

**Issue by PSNRigner** [electron/remote#103]
```
2021/12/28 15:30:11:334 TypeError: Cannot read properties of null (reading 'type')
    at metaToValue (C:\Program Files\Badlion Client\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:250:14)
    at Object.getBuiltin (C:\Program Files\Badlion Client\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:360:12)
    at Object.get [as app] (C:\Program Files\Badlion Client\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\remote.js:398:28)
    at Object.get [as app] (C:\Program Files\Badlion Client\resources\app.asar\node_modules\@electron\remote\dist\src\renderer\index.js:4:80)
    at file:///C:/Program%20Files/Badlion%20Client/resources/app.asar/app/updater.js:37:38
    at file:///C:/Program%20Files/Badlion%20Client/resources/app.asar/app/updater.js:66:2
```

Electron 15.3.4 is being used, also tried 16.0.5 and got the same issue.
It's erroring out on this line: 

```
import remote from '@electron/remote';
...
let { app } = remote; // errors out on this line
```
This is being called in the renderer process.

This appears to be some kind of race condition that only a very few number of users seem to have. We have seen several of these different stack traces for various areas in the remote module. We have also seen `sendSync` return null for some users (did a band aid for this one) in our own code....which seems to be the same issue that is happening here in the electron/remote code directly itself too in the `metaToValue` function call.

Looking for some advice/help here as to how to get this fixed. Like mentioned above, the main culprit is `sendSync` returning null.

**Comment by kasumiShieh** [comment]
I have encountered the same problem, it seems that it only appears when devtools is opening.

**Comment by john8329** [comment]
Same thing happening here, while calling `Menu.buildFromTemplate`, there's the `sendSync` call that sometimes returns `null`. I'm upgrading now to Electron 20 and see if it improves.

**Comment by chetbox** [comment]
We occasionally see the same issue in our Sentry crash logs.
