### ISSUE TITLE
Main process crashing with electron 11

### ISSUE THREAD

**Issue by Tchinmai7** [electron/remote#15]
I'm using the latest beta of electron 11 (beta.23), with electron/remote 1.0. I tried running my app, and I see a crash with the following stack trace.

    Uncaught Exception: TypeError: process.electronBinding is not a function
    at Object.<anonymous> (/my_app/ui/node_modules/@electron/remote/dist/src/main/objects-registry.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (my_app/ui/node_modules/@electron/remote/dist/src/main/server.js:8:44)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)

I'm initializing the remote module in my main process as 
`require('@electron/remote/main').initialize()`. `enableRemoteModule` is also set to true.

**Comment by abram** [comment]
Same issue here using Electron 11.0.1.

**Comment by nornagon** [comment]
Looks like https://github.com/electron/electron/pull/24191 broke this.

**Comment by nornagon** [comment]
This should be fixed with `@electron/remote@1.0.2`.
