### ISSUE TITLE
Error: No such module was linked: electron_common_v8_util

### ISSUE THREAD

**Issue by TheGoddessInari** [electron/remote#23]
When trying to run at all, it gets this with node 14.15.1 LTS.
```
internal/bootstrap/loaders.js:124
      mod = bindingObj[module] = getLinkedBinding(module);
                                 ^

Error: No such module was linked: electron_common_v8_util
    at process._linkedBinding (internal/bootstrap/loaders.js:124:34)
    at Object.exports.getElectronBinding (C:\Projects\rambox\node_modules\@electron\remote\dist\src\common\get-electron-binding.js:6:25)
    at Object.<anonymous> (C:\Projects\rambox\node_modules\@electron\remote\dist\src\main\objects-registry.js:4:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Projects\rambox\node_modules\@electron\remote\dist\src\main\server.js:8:44)
```

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by TheGoddessInari** [comment]
Hi, there was no template present in the repository, or on creating an issue.
This should suffice for information?

Platform: win32 (x64)
Electron: 11.0.3
Chromium: 87.0.4280.67

**Comment by Celludriel** [comment]
I am getting the same exception

`[electron] App threw an error during load
[electron] Error: No such module was linked: electron_common_v8_util
[electron]     at process._linkedBinding (internal/bootstrap/loaders.js:118:34)
[electron]     at Object.getElectronBinding (C:\workspaces\electron-test\x4-galaxy-creator-electron\node_modules\@electron\remote\dist\src\common\get-electron-binding.js:6:24)
[electron]     at Object.<anonymous> (C:\workspaces\electron-test\x4-galaxy-creator-electron\node_modules\@electron\remote\dist\src\main\server.js:12:39)
[electron]     at Module._compile (internal/modules/cjs/loader.js:967:30)
[electron]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
[electron]     at Module.load (internal/modules/cjs/loader.js:815:32)
[electron]     at Module._load (internal/modules/cjs/loader.js:727:14)
[electron]     at Function.Module._load (electron/js2c/asar.js:769:28)
[electron]     at Module.require (internal/modules/cjs/loader.js:852:19)
[electron]     at require (internal/modules/cjs/helpers.js:74:18)`

dependencies

`  "dependencies": {
    "@electron/remote": "^1.1.0",
    "electron-is-dev": "^1.2.0",
    "electron-squirrel-startup": "^1.0.0",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "cross-env": "^7.0.3",
    "honeycomb-grid": "^3.1.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.3",
    "react-scripts": "4.0.3",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^2.0.3",
    "web-vitals": "^1.1.1"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.54",
    "@electron-forge/maker-deb": "^6.0.0-beta.54",
    "@electron-forge/maker-rpm": "^6.0.0-beta.54",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.54",
    "@electron-forge/maker-zip": "^6.0.0-beta.54",
    "concurrently": "^5.2.0",
    "electron": "^9.4.4",
    "electron-devtools-installer": "^3.1.1",
    "wait-on": "^5.3.0"
  }
`

**Comment by bierzorutas** [comment]
same problem here

**Comment by seanaye** [comment]
Are there any updates on this?
