### ISSUE TITLE
Could not call remote method 'showSaveDialog'

### ISSUE THREAD

**Issue by vitor251093** [electron/remote#59]
I'm trying to use dialog.showSaveDialog, but it fails every time with the same stacktrace:

>     Error: Could not call remote method 'showSaveDialog'. Check that the method signature is correct. Underlying error: e is not iterable
>     Underlying stack: TypeError: e is not iterable
>     at electron/js2c/browser_init.js:49:1616
>     at setupDialogProperties (electron/js2c/browser_init.js:49:1681)
>     at saveDialog (electron/js2c/browser_init.js:49:2433)
>     at Object.showSaveDialog (electron/js2c/browser_init.js:49:5035)
>     at PROJECT_FOLDER/node_modules/@electron/remote/dist/src/main/server.js:454:71
>     at IpcMainImpl.<anonymous> (PROJECT_FOLDER/node_modules/@electron/remote/dist/src/main/server.js:313:27)
>     at IpcMainImpl.emit (events.js:315:20)
>     at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
>     at Object.emit (events.js:315:20)
> 
>     at PROJECT_FOLDER/node_modules/@electron/remote/dist/src/main/server.js:457:25
>     at IpcMainImpl.<anonymous> (PROJECT_FOLDER/node_modules/@electron/remote/dist/src/main/server.js:313:27)
>     at IpcMainImpl.emit (events.js:315:20)
>     at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
>     at Object.emit (events.js:315:20)

It's worth saying that showOpenDialog works like a charm. Sample code:

```
const remote = require('@electron/remote')
const {dialog} = remote

dialog.showSaveDialog(remote.getCurrentWindow(), {
        defaultPath: "default",
        filters: [{ name: 'WSI', extensions: ['wsi'] }],
        properties: {createDirectory:true, showOverwriteConfirmation:true}
}).then(result => {
        console.log(result);
});
```

Operating system: macOS 11.4 Beta (20F5065a)
electron version: 12.0.7
@electron/remote version: 1.1.0

Let me know if there is any other useful that may help.

**Comment by vitor251093** [comment]
Oh, and save `showSaveDialogSync` does not work either, with a similar stacktrace.

**Comment by vitor251093** [comment]
Just in case anyone else has this problem in macOS, I've made a workaround that does work, but which unfortunately is way more limited:

```
const path = require('path')
const fs = require('fs')
const fse = require('fs-extra')
const osascript = require('osascript')
const { v4: uuidv4 } = require('uuid')
const remote = require('@electron/remote')
const electronApp = remote.app
```

```
        osascript: {
            run: function(frameworks, script) {
                var firstLines = frameworks.map(f => "ObjC.import('" + f + "');")
                firstLines.push('var wrap = ObjC.wrap;')
                firstLines.push('var unwrap = ObjC.unwrap;')
                var finalScript = firstLines.join('\n') + '\n' + script
            
                return new Promise((resolve, reject) => {
                    osascript.eval(finalScript, function (err, data) {
                        if (err) {
                            if (err instanceof Error && err.message.includes('osascript: no such component "JavaScript"')) {
                                try {
                                    var filename = path.join(electronApp.getPath("temp"), uuidv4() + ".js")
                                    fs.writeFileSync(filename, finalScript, {encoding:'utf8'})
                                    osascript.file(filename, function (err2, data2) {
                                        try {
                                            fse.removeSync(filename)
                                        }
                                        catch(e){}
                                        
                                        if (err2) {
                                            return reject(err)
                                        }
                                        resolve(data2)
                                    })
                                    return
                                }
                                catch(e){}
                            }
                            return reject(err)
                        }
                        resolve(data)
                    });
                })
            },
        }
        showSaveDialog: async function({message, defaultPath, filters}) {
            if (filters.length > 1) {
                throw new Error("showSaveDialog only supports one filter in the filters property")
            }
            if (filters[0].extensions.length > 1) {
                throw new Error("showSaveDialog only supports one extension in the filters[0].extensions property")
            }
            var extension = filters[0].extensions[0]

            var defaultName = undefined
            var defaultLocation = undefined
            if (typeof defaultPath === 'string') {
                if (defaultPath.startsWith("/")) {
                    var ext = path.extname(defaultPath)
                    if (ext.length === 0) {
                        defaultLocation = defaultPath
                    } else {
                        defaultLocation = path.dirname(defaultPath)
                        defaultName = path.basename(defaultPath)
                    }
                } else {
                    defaultName = defaultPath
                }
            }
            if (defaultName !== undefined && !defaultName.endsWith("." + extension)) {
                defaultName += "." + extension
            }

            var props = []
            if (message !== undefined) {
                props.push("withPrompt: " + JSON.stringify(message))
            }
            if (defaultName !== undefined) {
                props.push("defaultName: " + JSON.stringify(defaultName))
            }
            if (defaultLocation !== undefined) {
                props.push("defaultLocation: " + JSON.stringify(defaultLocation))
            }
            var propsStr = props.join(", ")
            try {
                var val = await this.osascript.run([], `
                    app = Application.currentApplication()
                    app.includeStandardAdditions = true
                    try {
                        obj = (app.chooseFileName({${propsStr}})).toString()
                        obj = JSON.stringify(obj)
                    }
                    catch(e) {
                        null
                    }
                `)
                val = JSON.parse(val)
                if (val === null) {
                    return {canceled:true}
                }
                if (!val.endsWith("." + extension)) {
                    val += "." + extension
                }
                return {canceled:false, filePath:val}
            }
            catch(e) {
                throw new Error("Failed to show '" + message + "' prompt: " + e.message)
            }
        }
```

It does not allow the dialog to be presented in a sheet format, it supports only one extension, it only works in macOS, and it requires `fs-extra`, `osascript` and `uuid`, but at least it serves as a temporary replacement until that issue is fixed.

**Comment by nornagon** [comment]
`properties` should be an array of strings, not an object.
